#+OPTIONS: ':nil *:t -:t ::t <:t H:4 \n:nil ^:nil arch:headline author:t
#+OPTIONS: broken-links:nil c:nil creator:nil d:(not "LOGBOOK") date:t e:t
#+OPTIONS: email:nil f:t inline:t num:nil p:nil pri:nil prop:nil stat:t tags:t
#+OPTIONS: tasks:t tex:t timestamp:t title:t toc:nil todo:t |:t
#+TITLE: ~optional<T&>~
#+SUBTITLE: A Case Study
#+DATE: <2024-02-01 Thu>
#+AUTHOR: Steve Downey
#+EMAIL: sdowney2@bloomberg.net
#+LANGUAGE: en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+LATEX_CLASS: report
#+LATEX_CLASS_OPTIONS:
#+LATEX_HEADER:
#+LATEX_HEADER_EXTRA:
#+DESCRIPTION:
#+KEYWORDS:
#+SUBTITLE:
#+LATEX_COMPILER: pdflatex
#+OPTIONS: html-link-use-abs-url:nil html-postamble:nil html-preamble:t
#+OPTIONS: html-scripts:t html-style:t html5-fancy:nil tex:t
#+HTML_DOCTYPE: xhtml-strict
#+HTML_CONTAINER: div
#+DESCRIPTION:
#+KEYWORDS:
#+HTML_LINK_HOME:
#+HTML_LINK_UP:
#+HTML_MATHJAX:
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../etc/modus-vivendi-tinted.css"/>
#+HTML_HEAD_EXTRA:
#+INFOJS_OPT:
#+CREATOR:
#+LATEX_HEADER:
#+STARTUP: showall

#+OPTIONS: reveal_width:1600 reveal_height:900
#+REVEAL_TRANS: fade
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../etc/modus-vivendi-tinted.css" />

#+REVEAL_PLUGINS: (math markdown notes search zoom)
#+REVEAL_EXTRA_CSS: ../etc/modus-vivendi-tinted.css
#+REVEAL_THEME: ../etc/my_theme.css
#+REVEAL_EXTRA_CSS: ../etc/footer.css
#+REVEAL_TITLE_SLIDE: <h1>%t</h1><h2>%s</h2><h3>%A %a</h3>
# #+REVEAL_TITLE_SLIDE_BACKGROUND: ./title.png

# #+REVEAL_ROOT: https://cdn.jsdelivr.net/npm/reveal.js
#+REVEAL_ROOT: ./reveal.js
#+REVEAL_VERSION: 4

#+REVEAL_HLEVEL: 4
#+REVEAL_EXPORT_NOTES_TO_PDF: separate-page
#+REVEAL_DEFAULT_FRAG_STYLE: (appear)
#+REVEAL_EXTRA_OPTIONS: pdfSeparateFragments: true
#+OPTIONS: reveal_single_file:t

#+CITE_EXPORT: csl ../etc/chicago-author-date.csl
#+BIBLIOGRAPHY: ../etc/wg21.bib
#+BIBLIOGRAPHY: ../etc/local.bib

* Colophon

- Slideware: [[https://revealjs.com/][reveal.js]]
- Slide Preperation: [[https://gitlab.com/oer/org-re-reveal][org-re-reveal]]
- Fonts: [[https://www.brailleinstitute.org/freefont/][Atkinson Hyperlegible]] Next and Mono
- Color Themes: [[https://github.com/protesilaos/modus-themes][Modus]] Vivendi and Operandi Tinted

Intended to conform to [[https://www.w3.org/WAI/WCAG2AAA-Conformance][Web Content Accessibility Guidelines Level AAA]]


#+REVEAL_HTML: <a href="https://www.w3.org/WAI/WCAG2AAA-Conformance" title="Explanation of WCAG 2 Level AAA conformance">  <img height="32" width="88"       src="https://www.w3.org/WAI/WCAG22/wcag2.2AAA-blue" alt="Level AAA conformance, W3C WAI Web Content Accessibility Guidelines 2.2"></a>

#+begin_notes
Please try to be considerate when making presentations. Accessibility helps everyone.

Try to present working  code, even in slideware.

#+end_notes
* Standardising Optionals over References
Optionals were first proposed for C++ in 2005.

Optional<T> where T is constrained not to be a reference was added in 2017.

Optionals for lvalue references were voted in at the Sofia meeting in June, 2025

#+begin_notes

This talk will discuss the early history, starting with Boost.Optional and [cite/title/b:@N1878], and what the early concerns were for the reference specialization.  [cite/title/b:@P1175R0] ,  reproposed reference support for C++20, which was not adopted. [cite/title/b:@P1683R0],  in 2020 surveyed existing behavior of optional references in the wild, and pointed out the trap of assingment behaviour being state dependent. [cite/title/b:@P2988R0] picked up the torch again in 2023, of which revision 9 is the proposal which is design approved by the Library Evolution Working Group.

In 2024, the proposal to make optional a range, [cite/title/b:@P3168R0], as opposed to having a separate range of zero or one, was adopted. The reference implementation for ~optional<T&>~ and the test cases for ~views::maybe~ were used to vet the additional interfaces for optional range support. This merged implementation became one of the first Beman libraries, where the library and the optional reference proposal  benefited immensly from the visibility and feedback.

#+end_notes

** Why so long?
- What were the concerns that made the process take so long?
- How were concerns addressed?
- What did we end up with?
- What remains to be done?

#+begin_notes

The core of the difficulty has been that references are not values  and  types containing a reference do not have value semantics. References do not fit comfortably in the C++ type system. The core value semantic type that also has reference semantics is a pointer, but pointers have underconstrained and unsafe semantics. The long discussion has been a proxy for what reference semantic types should look like in value semantic types in the standard library, particularly for "sum" types, like ~expected~ and ~variant~.
#+end_notes

* Quick overview of optional<T>
- An owning type,
- with value semantics,
- with one additional out-of-band value.
#+begin_notes
#+end_notes

** Algebraically
~T + 1~

~std::variant<T, std::monostate>~

#+begin_notes
#+end_notes

** Core Use Case
#+transclude: [[file:./code/tests/slides.t.cpp::898237b6-5a21-439f-94be-b383a439e47e]] :lines 2- :src cpp :end "898237b6-5a21-439f-94be-b383a439e47e end"

*** C++26 Range Version
#+transclude: [[file:./code/tests/slides.t.cpp::848bce37-c7d0-48c4-ab5d-8f77cc436385]] :lines 2- :src cpp :end "848bce37-c7d0-48c4-ab5d-8f77cc436385 end"

** Default Optional Parameter
#+transclude: [[file:./code/tests/slides.t.cpp::f42adfde-5cf2-4c68-8453-83f85ccece63]] :lines 2- :src cpp :end "f42adfde-5cf2-4c68-8453-83f85ccece63 end"

#+transclude: [[file:./code/tests/slides.t.cpp::e1003632-659b-4d3b-a5a8-2045c1e7a67d]] :lines 2- :src cpp :end "e1003632-659b-4d3b-a5a8-2045c1e7a67d end"

#+begin_notes
#+end_notes
*  Quick overview of optional<T&>

- A non-owning type,
- with reference and value semantics,
- with one additional value representing the empty state.
#+begin_notes
#+end_notes
** Core Use Case
Looking up something for modification.
*** Today
#+transclude: [[file:./code/tests/slides.t.cpp::31481e6d-8401-4859-92b2-908af1c09fd2]] :lines 2- :src cpp :end "31481e6d-8401-4859-92b2-908af1c09fd2 end"

#+begin_notes
#+end_notes

*** With optional<int&>
#+transclude: [[file:./code/tests/slides.t.cpp::a945e141-bc08-4cf0-89ba-060068ffca00]] :lines 2- :src cpp :end "a945e141-bc08-4cf0-89ba-060068ffca00 end"

#+begin_notes
#+end_notes

** Optional Reference Parameter
Instead of a pointer:
#+transclude: [[file:./code/tests/slides.t.cpp::c089386c-ee92-4d95-87bb-10cf878b9882]] :lines 2- :src cpp :end "c089386c-ee92-4d95-87bb-10cf878b9882 end"

#+begin_notes
#+end_notes

*  Existing Problems with Optional
Construction and assignment from the underlying T or a type convertable to a T produces inevitable surprises and deep complication in the implementation.

Reasoning about overload sets is difficult for humans.
#+begin_notes
#+end_notes


* The Design Problems for References
** Assign or Rebind?
#+begin_src cpp
Cat fynn;
Cat loki;
optional<Cat&> maybeCat1;
optional<Cat&> maybeCat2{fynn};
maybeCat1 = fynn;
maybeCat2 = loki;
#+end_src
What do those assignments do?

Ought they be allowed?

State independence won out, eventually.

*ALWAYS* rebind.
#+begin_notes
What assignment does is not dependent on the state of the optional. It always rebinds the "reference", which is not possible with a C++ reference in a struct.
#+end_notes
** Non-generic template
~optional<T&>~ violates genericity.

The "~vector<bool>~" problem only for an entire value category.

Reference categories are weird and non-generic.
#+begin_notes
#+end_notes

* Design Choices
** src_cpp[:exports code]{make_optional()}
~make_optional()~ was largely supplanted by CTAD.

~make_optional<T&>()~ creates an ~optional<T>~.

Doing otherwise would have been worse.

#+begin_notes
#+end_notes
** Value Category's Affect on src_cpp[:exports code]{optional<T&>::value() &&}
What should src_cpp[:exports code]{optional<T&>::value() &&;} return?

Choose to model pointers, a reference semantic value type.

The value category of the object does not affect value category of the referent.

Otherwise an rvalue src_cpp[:exports code]{optional<T&>} could enable moves from the referent.
#+begin_notes
#+end_notes
** Shallow vs. Deep ~const~
What should src_cpp[:exports code]{optional<T&>::value() const;} return?

Choose to model pointers, a reference semantic value type.

A ~const~ pointer is not a pointer to ~const~.

All langauge references are ~const~.

An src_cpp[:exports code]{optional<T&>} is a reference semantic type.

Not a reference.

#+begin_notes
#+end_notes
** Conditional Explicit
Is a spelled out src_cpp[:exports code]{optional<T&>(x)} required to construct an ~optional<T&>~?

Or can an ~optional<T&>~ be constructed implicitly from a ~t~?

I would have preferred requiring explicit, but it was too painful in practice.

Lack of ~explicit~ makes the type exponentially more complex.

There are more interactions between member functions.
#+begin_notes
#+end_notes
** src_cpp[:exports code]{value_or()}
What should src_cpp[:exports code]{optional<T&>::value_or(U &&u);} return?

What is the "value type" for an optional?

All choices are surprising to someone.

Chose to return T, as that seems least dangerous.

It is what ~optional<T>~ does.

#+begin_notes
Future work: generic src_cpp[:exports code]{nullable} functions.
#+end_notes
** ~in_place_t~ construction
There is no "place" to construct in to.
#+begin_notes
#+end_notes
** Converting assignment
Avoid conversions that produce temporaries.

Avoid confusion with src_cpp[:exports code]{optional<U&>} or src_cpp[:exports code]{optional<T>} constructors.

Large /overload sets/ are difficult to reason about.

#+begin_notes
#+end_notes
* Reification Principles
** Construction from temporary
Avoid taking references to temporaries.

Rules out some safe cases, disallows many dangerous cases.
#+begin_notes
#+end_notes
** Deleting dangling overloads
Delete, rather than remove via ~concept~,  function overloads that produce dangling references.

#+begin_notes
#+end_notes
** Assignment of src_cpp[:exports code]{optional<T&>}
Assignment of an optional<T&> is equivalent to a pointer copy.

All assignments are through the single function.
#+begin_notes
#+end_notes
* Project Beman
** Began last year at C++Now 2024

Not a requirement for Standardization.

Details matter.

#+begin_notes
LEWG is getting better at asking for implementation of exact proposal.
#+end_notes

** Pre-existing smd::optional
Confirmed at Tokyo, live, that the range-ification would work for my test cases for ~views::maybe~.

Unfortunately ~smd::optional~ used early-Modern CMake.

This meant rework to bring it to current standards.

#+begin_notes
#+end_notes

** The ref-stealing bug found
#+begin_src cpp
Cat fynn;
std::optional<Cat&> maybeCatRef{fynn};
std::optional<Cat> maybeCat;
maybeCat = std::move(maybeCatRef);
// fynn is moved from
#+end_src

Now fixed.
*** The fix
Don't move the result of operator*, move the rhs and apply operator*().

#+begin_src cpp
//instead of
*std::move(rhs)
// use
std::move(*rhs)
#+end_src

Because
#+begin_src cpp
std::optional<T&>::operator*() && -> T&; // overload not actually present
#+end_src

does not return an rvalue reference.

#+begin_notes

#+end_notes
* The Modal Use-Case
The expected most common use is for looking up something and failure is not exceptional.

#+begin_src cpp
constexpr optional<mapped_type&> get(const key_type& k);
#+end_src

We plan to add this to associative containers for C++29.

** P3091 by Pablo Halpern
Better Lookups for ~map~, ~unordered_map~, and ~flat_map~



* Questions?
Remember a question starts with:

#+ATTR_REVEAL: :frag (current-visible)
- who
- what
- when
- where
- how
- why

#+REVEAL: split
or
- A propositional statement :: a statement that has a truth value, either true or false, but not both.

#+REVEAL: split
and goes up at the end.

#+REVEAL: split
#+begin_quote
"More of a comment than a question ..."
#+end_quote
Is a propositional statement, but hold them for a moment.
* Comments?

* Thank You!

* Bibliography
   :PROPERTIES:
   :reveal_extra_attr: data-visibility="hidden"
   :END:

#+CITE_EXPORT: csl chicago-author-date.csl
#+print_bibliography:

# Local Variables:
# org-html-htmlize-output-type: css
# End:
